FROM golang:1.21.7-alpine3.17 AS build
WORKDIR /src
COPY . .
RUN apk add --no-cache gcc musl-dev
RUN go build -o explorer-collector ./cmd/collector/

FROM alpine:3.17
COPY --from=build /src/explorer-collector /bin/
ENTRYPOINT ["/bin/explorer-collector"]
