FROM golang:1.23.2-alpine AS build
WORKDIR /src
COPY . .
RUN apk add --no-cache gcc musl-dev
RUN go build -o explorer-api ./cmd/apiserver/

FROM alpine:3.17
COPY --from=build /src/explorer-api /bin/
EXPOSE 5000
ENTRYPOINT ["/bin/explorer-api"]
