FROM golang:1.15.6-alpine3.12 AS build
WORKDIR /src
COPY . .
RUN go build -o explorer-collector ./cmd/collector/

FROM alpine:3.12
COPY --from=build /src/explorer-collector /bin/
ENTRYPOINT ["/bin/explorer-collector"]
