FROM golang:1.22.3-alpine AS build
WORKDIR /src
COPY . .
RUN apk add --no-cache gcc musl-dev
RUN go build -o explorer-custom-api ./cmd/api/

FROM alpine:3.17
COPY --from=build /src/explorer-custom-api /bin/
EXPOSE 5000
ENTRYPOINT ["/bin/explorer-custom-api"]
