name: Publish

on:
  release:
    types: [published]

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta apiserver
        id: meta_apiserver
        uses: docker/metadata-action@v4
        with:
          images: spacemeshos/explorer-apiserver

      - name: Docker meta collector
        id: meta_collector
        uses: docker/metadata-action@v4
        with:
          images: spacemeshos/explorer-collector

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          repository: spacemeshos/explorer-apiserver
          file: ./Dockerfile.apiserver
          push: true
          tags: ${{ steps.meta_apiserver.outputs.tags }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          repository: spacemeshos/explorer-collector
          file: ./Dockerfile.collector
          push: true
          tags: ${{ steps.meta_collector.outputs.tags }}

