name: Publish

on:
  release:
    types: [published]

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta stats api
        id: meta_statsapi
        uses: docker/metadata-action@v5
        with:
          images: spacemeshos/explorer-stats-api

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          repository: spacemeshos/explorer-stats-api
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta_statsapi.outputs.tags }}
